# Generated by Django 5.0.1 on 2024-01-30 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selected_products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selectedproduct',
            old_name='quantity',
            new_name='ordered_quantity',
        ),
    ]
