# Generated by Django 5.0.1 on 2024-01-27 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_partonymic_customuser_patronymic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='patronymic',
            new_name='patronymic_name',
        ),
    ]
