"""
Django settings for flower_shop project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

from django.urls import reverse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h_ar#s80a4y3=wvh-gir!h#rr4**v8tn6z^ct04&3&5$r@iasv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'general',
    'products',
    'companies',
    'selected_products',
    'orders',
    'product_properties',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'flower_shop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'flower_shop.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'  # https://docs.djangoproject.com/en/5.0/ref/settings/#language-code
# http://www.i18nguy.com/unicode/language-identifiers.html

TIME_ZONE = 'Europe/Moscow'  # https://docs.djangoproject.com/en/5.0/ref/settings/#std-setting-TIME_ZONE
# https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = 'media/'  # https://docs.djangoproject.com/en/5.0/ref/settings/#media-url
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # https://docs.djangoproject.com/en/5.0/ref/settings/#media-root

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# По умолчанию переадресует на '/accounts/login/'.
# У  нас нет такой страницы. Создавать ее смысла нет - слишком долго,
# да и в задании ее не было. Поэтому просто переадресуем на главную.

# settings.py загружается раньше всего остального проекта.
# Т.е. раньше, чем загрузятся приложения и urlpattern.
# Поэтому функция reverse не заработает.
# Придется захардкодить путь.

# https://docs.djangoproject.com/en/5.0/ref/settings/#login-redirect-url

LOGIN_REDIRECT_URL = '/'

# См. комментарий к LOGIN_REDIRECT_URL по поводу вынужденной
# необходимости захардкодить url.
# https://docs.djangoproject.com/en/5.0/ref/settings/#logout-redirect-url
LOGOUT_REDIRECT_URL = '/about/'

AUTH_USER_MODEL = "accounts.CustomUser"  # https://docs.djangoproject.com/en/5.0/ref/settings/#auth-user-model
