# Generated by Django 5.0.1 on 2024-01-24 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered',
            new_name='ordered_at',
        ),
    ]
