# Generated by Django 5.0.1 on 2024-01-24 18:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Наименование')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото. Рекомендовано 500 x 500 px')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Остаток товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_properties.category', verbose_name='Категория / Вид товара')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_properties.color', verbose_name='Цвет')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_properties.country', verbose_name='Страна-производитель')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
