# Generated by Django 5.0.1 on 2024-01-23 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_properties', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_properties.category', verbose_name='Категория / Вид товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_properties.color', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='product',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_properties.country', verbose_name='Страна-производитель'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
