# Generated by Django 5.0.1 on 2024-01-20 13:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Наименование')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Остаток товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Категория / Вид товара')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.color', verbose_name='Цвет')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.country', verbose_name='Страна-производитель')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
