# Generated by Django 5.0.1 on 2024-01-20 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_goods'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goods',
            new_name='Product',
        ),
    ]
